# Generated by Django 2.2.1 on 2019-05-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleaudiodb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio_info',
            field=models.FileField(default='File Not Found', upload_to='audio/'),
        ),
    ]
