# Generated by Django 2.2.1 on 2019-05-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleaudiodb', '0004_document_uploadfileform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
